exception: Convert E_STRICT errors to E_USER_NOTICE
E_STRICT is deprecated in PHP 8.4.0.

MediaWiki (and almost all extensions) no longer produces errors at this
level.
To not break the compatibility, let's converts all E_STRICT level errors
to E_USER_NOTICE, which is also mapped to warning severity.

Using '@' operator to avoid generating the deprecation warning of
E_STRICT.

This should addresses the deprecation warning of E_STRICT when another
warning or error is raised.

Bug: T375707
Change-Id: I5937cacdf5b01614042a06d4deb5112ffff51727