mediawiki.page.ready: Fix undefined `mw.user` during temp user logout
Follows-up Ib62cdb5ba7 (ab89fff633), which added a call to mw.user
without declaring a dependency.

Clicking "Exit session" consistently fails on a plain install with:

```
Uncaught TypeError: mw.user.isTemp is not a function
    logoutViaPost ready.js:195
```

Bug: T378163
Change-Id: I9c4a788228a70131700769d3fd2a991c6cb0cd27
(cherry picked from commit d3ddfd942592a6a2b511b34ba8872e51d51377c6)